[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "."
]

[tool.mypy]
disallow_untyped_defs = true
explicit_package_bases = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
